import type { Metadata } from "next"; 

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default function ProductDetailsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
        <h4> Product features</h4>
      </body>
    </html>
  );
}
