import Link from "next/link";

export const metadata = { 
    title: "Swapnil",
    description: "Generated by Swapnil",
}

export default function About() {
    return (
      <div>
        <Link href='/'>Home</Link>
        <h3>About</h3>
      </div>
    );
  }
  